---

# call the collection repository sync module

- name: "Sync the collection repository - {{ collection_repository.name }}"
  connection: local
  infra.ah_configuration.collection_repository_sync:
    ah_host: "{{ ansible_fqdn }}"
    ah_path_prefix: "{{ ah_api_path_prefix | default('automation_hub') }}"
  #  ah_token: "{{ ah_api_token | default(omit) }}"
    ah_password: "{{ ah_password | default(omit) }}"
    ah_username: "{{ ah_username | default(omit) }}"
    name: "{{ collection_repository.name }}"
    interval: "{{ ah_update_interval_sec | default(omit) }}"
    timeout: "{{ ah_request_timeout_sec | default(omit) }}"
    validate_certs: "{{ ah_validate_certs | default(omit) }}"
    wait: "{{ collection_repository.sync_wait | default(omit) }}"
