---

- name: "Install package {{ rhel_package.names }}"
  ansible.builtin.dnf:
    name: "{{ rhel_package.names }}"
    allow_downgrade: "{{ rhel_package.allow_downgrade | default(false) }}"
    allowerasing: "{{ rhel_package.allow_erasing | default(false) }}"
    autoremove: "{{ rhel_package.autoremove | default(false) }}"
    best: "{{ rhel_package.best | default(false) }}"
    bugfix: "{{ rhel_package.bugfix | default(false) }}"
    cacheonly: "{{ rhel_package.cacheonly | default(false) }}"
    conf_file: "{{ rhel_package.conf_file | default('/etc/dnf/dnf.conf') }}"
    disable_excludes: "{{ rhel_package.disable_excludes | default(false) }}"
    disable_gpg_check: "{{ rhel_package.disable_gpg_check | default(false) }}"
    disable_plugin: "{{ rhel_package.disable_plugins | default(false) }}"
    disablerepo: "{{ rhel_package.disablerepos | default(omit) }}"
    download_dir: "{{ rhel_package.download_dir | default(omit) }}"
    download_only: "{{ rhel_package.download_only | default(false) }}"
    enable_plugin: "{{ rhel_package.enable_plugins | default(omit) }}"
    enablerepo: "{{ rhel_package.enablerepos | default(omit) }}"
    exclude: "{{ rhel_package.excludes | default(omit) }}"
    installroot: "{{ rhel_package.installroot | default(omit) }}"
    install_weak_deps: "{{ rhel_package.install_weak_deps | default(omit) }}"
    lock_timeout: "{{ rhel_package.lock_timeout | default(omit) }}"
    nobest: "{{ rhel_package.nobest | default(omit) }}"
    releasever: "{{ rhel_package.releasever | default(omit) }}"
    security: "{{ rhel_package.security | default(omit) }}"
    skip_broken: "{{ rhel_package.skip_broken | default(omit) }}"
    update_cache: "{{ rhel_package.update_cache | default(omit) }}"
    update_only: "{{ rhel_package.update_only | default(omit) }}"
    use_backend: "{{ rhel_package.use_backend | default(omit) }}"
    validate_certs: "{{ rhel_package.validate_certs | default(omit) }}"
    state: "{{ rhel_package.state | default('present') }}"
